name: Deploy Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

  steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: C/C++ dev tools
      run: |
        sudo apt update
        sudo apt-get install -y build-essential gcc-multilib g++-multilib
    
    - name: build
      run: |
        make COMPILER=g++ CFG=release -j2
    
    # - name: upload bins
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: linux-x86
    #     path: |
    #       linux/releases/vpc
